name: Iso2Mesh CI

on: [push, pull_request]

jobs:
  octave_test:
    name: Octave tests
    strategy:
      # provided octave versions: ubuntu-20.04 = 5.2, ubuntu-22.04 = 6.4, macos-12 = 8.1, windows-2019 = 7.3
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04, macos-12, windows-2019]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Install dependencies
        run: |
          [[ "$RUNNER_OS" == "Linux" ]] && sudo apt-get update && sudo apt-get install -y octave cmake libcgal-dev libsuperlu-dev libsuitesparse-dev libgmp-dev libtbb-dev octave-image
          if [[ "$RUNNER_OS" == "macOS" ]]; then
            brew install octave
          fi
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            curl --retry 3 -kL http://cdimage.debian.org/mirror/gnu.org/gnu/octave/windows/octave-5.2.0-w64-64.7z --output octave_5.2.0.7z
            7z x octave_5.2.0.7z -ooctave -y
            echo "$PWD/octave/octave-5.2.0-w64-64/mingw64/bin" >> $GITHUB_PATH
          fi
      - name: Install octave-image (Windows only)
        if: ${{ runner.os == 'Windows' }}
        run: octave-cli --eval "pkg install -forge image"
      - name: Run octave test
        run: |
          octave-cli --version
          octave-cli --eval "addpath(pwd);cd sample; tic; demo_vol2mesh_ex1; toc; demo_vol2mesh_ex1b; demo_vol2mesh_ex1c"
          octave-cli --eval "addpath(pwd);cd sample; tic; demo_vol2mesh_ex2; toc"
          octave-cli --eval "addpath(pwd);cd sample; tic; demo_surf2mesh_ex1; toc"
          octave-cli --eval "addpath(pwd);cd sample; tic; demo_directplc_ex1; toc"
          octave-cli --eval "addpath(pwd);cd sample; tic; demo_grayscale_ex1; toc"
          octave-cli --eval "addpath(pwd);cd sample; tic; demo_shortcut_ex1; toc"
          octave-cli --eval "addpath(pwd);cd sample; tic; demo_surf2vol_ex1; toc"
          octave-cli --eval "addpath(pwd);cd sample; tic; demo_label_sizing; toc"
          octave-cli --eval "addpath(pwd);cd sample; tic; demo_qmeshcut_ex1; toc"
      - name: Rebuild binaries
        if: ${{ runner.os == 'Linux' }}   # use these variables to limit a step only on a specific OS
        run: |
          cd tools
          make
          ls -lt ../bin/*

  matlab_test:
    name: MATLAB test
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-12, windows-2019]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v1
        with:
          release: R2022a
      - name: Run MATLAB test
        uses: matlab-actions/run-command@v1
        with:
          command: addpath(pwd);cd sample; tic; demo_vol2mesh_ex1; toc; demo_vol2mesh_ex1b; toc; demo_vol2mesh_ex1c; toc
      - name: Run MATLAB examples
        uses: matlab-actions/run-command@v1
        with:
          command: addpath(pwd);cd sample; tic; demo_vol2mesh_ex2; toc
      - name: Run MATLAB examples
        uses: matlab-actions/run-command@v1
        with:
          command: addpath(pwd);cd sample; tic; demo_surf2mesh_ex1; demo_directplc_ex1; toc; demo_grayscale_ex1; toc
      - name: Run MATLAB examples
        uses: matlab-actions/run-command@v1
        with:
          command: addpath(pwd);cd sample; tic; demo_shortcut_ex1; demo_surf2vol_ex1; toc; demo_label_sizing; toc
      - name: Run MATLAB examples
        uses: matlab-actions/run-command@v1
        with:
          command: addpath(pwd);cd sample; tic; demo_qmeshcut_ex1; toc

